from __future__ import annotations

import csv
import json
import os
import sqlite3
from contextlib import closing
from functools import lru_cache
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = Path(os.getenv("MALAPP_DATA_DIR", str(ROOT / "data"))).expanduser().resolve()
DB_PATH = DATA_DIR / "mvp.db"


DEFAULT_VALIDATION_CSV = ROOT / "training_artifacts" / "xgb_selected_20260616" / "test_set_for_app.csv"


def load_validation_set(path: Path = DEFAULT_VALIDATION_CSV) -> dict[str, Any]:
    """Load the exported XGBoost validation/test set for browser comparison.

    The file is generated by tools/train_selected_xgb_from_excels.py.  It is a
    labelled evaluation set, so the UI can compare label vs model verdict
    without running the full dual-model judgement pipeline again.
    """
    if not path.exists():
        return {"path": str(path), "exists": False, "summary": empty_summary(), "items": []}
    stat = path.stat()
    rows = _cached_rows(str(path), stat.st_mtime_ns, stat.st_size)
    summary = summarize(rows)
    return {"path": str(path), "exists": True, "summary": summary, "items": rows}


def list_validation_items(
    *,
    limit: int = 200,
    offset: int = 0,
    label: str = "",
    result: str = "",
    query: str = "",
    judged: bool = False,
    pending: bool = False,
    order: str = "",
) -> dict[str, Any]:
    data = load_validation_set()
    rows = data["items"]
    report_index = saved_report_index()
    judged_summary = summarize_app_judgements(rows, report_index)
    filtered = [row for row in rows if match_filters(row, label=label, result=result, query=query)]
    if judged:
        filtered = [row for row in filtered if row_key(row) in report_index]
    elif pending:
        filtered = [row for row in filtered if row_key(row) not in report_index]
    if order == "stratified":
        filtered = stratified_rows(filtered)
    start = max(0, offset)
    end = start + max(1, min(limit, 1000))
    return {
        "path": data["path"],
        "exists": data["exists"],
        "summary": data["summary"],
        "judged_total": judged_summary["total"],
        "judged_summary": judged_summary,
        "pending_total": len(rows) - judged_summary["total"],
        "judged_only": judged,
        "pending_only": pending,
        "total": len(filtered),
        "offset": start,
        "limit": end - start,
        "items": [compact_item(row, report_index.get(row_key(row))) for row in filtered[start:end]],
    }


def summarize_app_judgements(
    rows: list[dict[str, Any]],
    report_index: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    summary = {
        "total": 0,
        "correct": 0,
        "incorrect": 0,
        "review": 0,
        "accuracy": None,
        "labels": {"malicious": 0, "benign": 0},
    }
    for row in rows:
        report = report_index.get(row_key(row))
        if not report:
            continue
        verdict = str((report.get("decision") or {}).get("verdict") or "").strip().lower()
        if not verdict:
            continue
        summary["total"] += 1
        gold = row["_gold_label"]
        summary["labels"][gold] = summary["labels"].get(gold, 0) + 1
        if verdict == "suspicious":
            summary["review"] += 1
        elif verdict == gold:
            summary["correct"] += 1
        else:
            summary["incorrect"] += 1
    decided = summary["correct"] + summary["incorrect"]
    summary["accuracy"] = safe_div(summary["correct"], decided)
    return summary


def stratified_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Interleave labels deterministically while preserving their overall ratio."""
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        groups.setdefault(str(row.get("_gold_label") or "other"), []).append(row)
    ranked: list[tuple[float, str, int, dict[str, Any]]] = []
    for label, items in groups.items():
        size = len(items)
        for index, row in enumerate(items):
            ranked.append(((index + 0.5) / size, label, index, row))
    ranked.sort(key=lambda item: (item[0], item[1], item[2]))
    return [item[3] for item in ranked]


def get_validation_sample(md5: str) -> dict[str, Any]:
    target = str(md5 or "").strip().upper()
    if not target:
        raise ValueError("md5 is required")
    data = load_validation_set()
    for row in data["items"]:
        if str(row.get("md5", "")).upper() == target:
            return sample_payload(row)
    raise KeyError(f"validation sample not found: {md5}")


@lru_cache(maxsize=4)
def _cached_rows(path: str, mtime_ns: int, size: int) -> list[dict[str, Any]]:
    del mtime_ns, size
    rows: list[dict[str, Any]] = []
    with Path(path).open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for raw in reader:
            row = {str(k or "").strip(): clean_value(v) for k, v in raw.items()}
            row["_gold_label"] = gold_label(row)
            row["_pred_label"] = predicted_label(row)
            row["_compare_result"] = compare_result(row["_gold_label"], row["_pred_label"])
            rows.append(row)
    return rows


def summarize(rows: list[dict[str, Any]]) -> dict[str, Any]:
    summary = empty_summary()
    summary["total"] = len(rows)
    for row in rows:
        label = row["_gold_label"]
        pred = row["_pred_label"]
        result = row["_compare_result"]
        summary["labels"][label] = summary["labels"].get(label, 0) + 1
        summary["predictions"][pred] = summary["predictions"].get(pred, 0) + 1
        summary["results"][result] = summary["results"].get(result, 0) + 1
        if result != "review":
            summary["decided_total"] += 1
            if result == "correct":
                summary["decided_correct"] += 1
    positive = [row for row in rows if row["_gold_label"] == "malicious"]
    negative = [row for row in rows if row["_gold_label"] == "benign"]
    tp = sum(1 for row in positive if row["_pred_label"] == "malicious")
    fn = sum(1 for row in positive if row["_pred_label"] == "benign")
    fp = sum(1 for row in negative if row["_pred_label"] == "malicious")
    tn = sum(1 for row in negative if row["_pred_label"] == "benign")
    summary["confusion"] = {"tp": tp, "fn": fn, "fp": fp, "tn": tn}
    summary["malicious_recall"] = safe_div(tp, tp + fn)
    summary["malicious_precision"] = safe_div(tp, tp + fp)
    summary["decided_accuracy"] = safe_div(summary["decided_correct"], summary["decided_total"])
    return summary


def empty_summary() -> dict[str, Any]:
    return {
        "total": 0,
        "labels": {"malicious": 0, "benign": 0},
        "predictions": {"malicious": 0, "suspicious": 0, "benign": 0},
        "results": {"correct": 0, "incorrect": 0, "review": 0},
        "decided_total": 0,
        "decided_correct": 0,
        "decided_accuracy": None,
        "malicious_recall": None,
        "malicious_precision": None,
        "confusion": {"tp": 0, "fn": 0, "fp": 0, "tn": 0},
    }


def clean_value(value: Any) -> str:
    return "" if value is None else str(value).strip()


def gold_label(row: dict[str, Any]) -> str:
    for key in ("gold_label", "source_malicious"):
        text = str(row.get(key, "")).strip().lower()
        if text in {"1", "true", "yes", "y", "malicious", "恶意", "100"}:
            return "malicious"
        if text in {"0", "false", "no", "n", "benign", "良性", "white", "白样本"}:
            return "benign"
    return "malicious" if row.get("label_source") == "manual_conflict" else "benign"


def predicted_label(row: dict[str, Any]) -> str:
    text = str(row.get("xgb_verdict") or "").strip().lower()
    if text in {"malicious", "恶意"}:
        return "malicious"
    if text in {"benign", "良性"}:
        return "benign"
    return "suspicious"


def compare_result(gold: str, pred: str) -> str:
    if pred == "suspicious":
        return "review"
    return "correct" if gold == pred else "incorrect"


def match_filters(row: dict[str, Any], *, label: str, result: str, query: str) -> bool:
    if label and row["_gold_label"] != label:
        return False
    if result and row["_compare_result"] != result:
        return False
    if query:
        haystack = " ".join(str(row.get(key, "")) for key in ("md5", "app_name", "package_name", "virus_name", "label_source"))
        if query.lower() not in haystack.lower():
            return False
    return True


def compact_item(row: dict[str, Any], report: dict[str, Any] | None = None) -> dict[str, Any]:
    item = {
        "md5": row.get("md5", ""),
        "app_name": row.get("app_name", ""),
        "package_name": row.get("package_name", ""),
        "gold_label": row["_gold_label"],
        "pred_label": row["_pred_label"],
        "compare_result": row["_compare_result"],
        "xgb_probability": as_float(row.get("xgb_probability")),
        "label_source": row.get("label_source", ""),
        "engine_360_score": row.get("engine_360_score", ""),
        "engine_cm_score": row.get("engine_cm_score", ""),
        "virus_name": row.get("virus_name", ""),
    }
    if report:
        decision = report.get("decision") or {}
        item["app_report"] = {
            "report_id": report.get("report_id", ""),
            "verdict": decision.get("verdict", ""),
            "final_score": as_float(decision.get("final_score")),
            "risk_level": decision.get("risk_level", ""),
            "created_at": report.get("created_at", ""),
        }
    return item


def saved_report_index() -> dict[str, dict[str, Any]]:
    index: dict[str, dict[str, Any]] = {}
    if not DB_PATH.exists():
        return index
    try:
        with closing(sqlite3.connect(DB_PATH)) as conn:
            rows = conn.execute(
                """
                SELECT id, sample_id, verdict, final_score, risk_level, created_at
                FROM judgements
                ORDER BY created_at DESC
                """
            ).fetchall()
    except sqlite3.Error:
        return index
    for report_id, sample_id, verdict, final_score, risk_level, created_at in rows:
        key = str(sample_id or "").strip().upper()
        if key and key not in index:
            index[key] = {
                "report_id": report_id,
                "created_at": created_at,
                "decision": {
                    "verdict": verdict,
                    "final_score": final_score,
                    "risk_level": risk_level,
                },
            }
    return index


def report_key(report: dict[str, Any]) -> str:
    sample = report.get("sample") if isinstance(report.get("sample"), dict) else {}
    for key in ("md5", "sample_id", "sha256", "sha1"):
        text = str(sample.get(key) or "").strip().upper()
        if text:
            return text
    return ""


def row_key(row: dict[str, Any]) -> str:
    for key in ("md5", "sample_id", "sha256", "sha1"):
        text = str(row.get(key) or "").strip().upper()
        if text:
            return text
    return ""


def sample_payload(row: dict[str, Any]) -> dict[str, Any]:
    payload = {key: value for key, value in row.items() if value not in ("", None) and not key.startswith("_")}
    payload["gold_label"] = row["_gold_label"]
    payload["validation_gold_label"] = row["_gold_label"]
    payload["validation_pred_label"] = row["_pred_label"]
    payload["validation_compare_result"] = row["_compare_result"]
    return payload


def as_float(value: Any) -> float | None:
    try:
        return round(float(value), 6)
    except Exception:
        return None


def safe_div(numerator: int, denominator: int) -> float | None:
    if denominator <= 0:
        return None
    return round(numerator / denominator, 6)
